// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../plugin/models.dart';
import '../plugin/plugin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Return `true` if `stream` has a non-empty HTTPS/HTTP URL and is not expired
/// (with a safety margin of [`EXPIRY_MARGIN_SECS`]).
Future<bool> isStreamUsable({required StreamSource stream}) =>
    RustLib.instance.api
        .crateApiDownloaderResolverIsStreamUsable(stream: stream);

/// Pick the best stream from `streams` given a quality preference string.
/// Falls back to progressively wider selections before giving up.
Future<StreamSource?> selectBestStream(
        {required List<StreamSource> streams, required String preference}) =>
    RustLib.instance.api.crateApiDownloaderResolverSelectBestStream(
        streams: streams, preference: preference);

/// Resolve the best stream for `task_id`, using the cached stream when still
/// valid or fetching a fresh one from the plugin manager otherwise.
///
/// Also derives and stores `file_name` / `target_path` on first successful
/// resolution so the rest of the pipeline always has a non-empty target.
///
/// Returns `Err` if the task was cancelled while waiting on the plugin call.
Future<StreamSource> resolveStream(
        {required ArcMutexManagedTask task,
        required PluginManager pluginManager}) =>
    RustLib.instance.api.crateApiDownloaderResolverResolveStream(
        task: task, pluginManager: pluginManager);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < Mutex < ManagedTask > >>>
abstract class ArcMutexManagedTask implements RustOpaqueInterface {}
