// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../plugin/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `remove_file_if_exists`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProgressUpdate`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `download_task_blocking`

/// Write title, artist, album, and cover art to the audio file at `file_path`
/// using the `lofty` crate.
///
/// This is a best-effort operation. Callers should treat errors as warnings
/// rather than hard failures — the audio content itself is intact.
Future<void> writeAudioMetadata(
        {required Client client,
        required String filePath,
        required Track track}) =>
    RustLib.instance.api.crateApiDownloaderTransferWriteAudioMetadata(
        client: client, filePath: filePath, track: track);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Client>>
abstract class Client implements RustOpaqueInterface {}
