// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../plugin/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EventHub`, `ManagedTask`, `PersistedDownloadTask`, `TransferOutcome`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from_persisted`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `attach`, `emit`, `from_persisted`, `new`

@freezed
sealed class DownloadManagerEvent with _$DownloadManagerEvent {
  const DownloadManagerEvent._();

  /// Emitted on every meaningful state/progress change.
  const factory DownloadManagerEvent.taskUpdated(
    DownloadTaskSnapshot field0,
  ) = DownloadManagerEvent_TaskUpdated;

  /// Emitted once when the file is fully written. Dart must persist it to
  /// the database then call `acknowledge_persisted`.
  const factory DownloadManagerEvent.taskCompletedPendingAck(
    DownloadTaskSnapshot field0,
  ) = DownloadManagerEvent_TaskCompletedPendingAck;

  /// Emitted after a task is fully removed (ack or cancel).
  const factory DownloadManagerEvent.taskRemoved({
    required String taskId,
  }) = DownloadManagerEvent_TaskRemoved;

  /// Emitted once on startup summarising state reconciliation.
  const factory DownloadManagerEvent.recoverySummary({
    required int restored,
    required int cleaned,
  }) = DownloadManagerEvent_RecoverySummary;
}

class DownloadTaskSnapshot {
  final String taskId;
  final Track track;
  final String fileName;
  final String targetPath;
  final String tempPath;
  final DownloadTaskState state;
  final double progress;
  final BigInt bytesDownloaded;
  final BigInt? totalBytes;
  final String? message;
  final String? lastError;

  const DownloadTaskSnapshot({
    required this.taskId,
    required this.track,
    required this.fileName,
    required this.targetPath,
    required this.tempPath,
    required this.state,
    required this.progress,
    required this.bytesDownloaded,
    this.totalBytes,
    this.message,
    this.lastError,
  });

  @override
  int get hashCode =>
      taskId.hashCode ^
      track.hashCode ^
      fileName.hashCode ^
      targetPath.hashCode ^
      tempPath.hashCode ^
      state.hashCode ^
      progress.hashCode ^
      bytesDownloaded.hashCode ^
      totalBytes.hashCode ^
      message.hashCode ^
      lastError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadTaskSnapshot &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          track == other.track &&
          fileName == other.fileName &&
          targetPath == other.targetPath &&
          tempPath == other.tempPath &&
          state == other.state &&
          progress == other.progress &&
          bytesDownloaded == other.bytesDownloaded &&
          totalBytes == other.totalBytes &&
          message == other.message &&
          lastError == other.lastError;
}

enum DownloadTaskState {
  queued,
  resolving,
  downloading,
  paused,
  retrying,
  writingMetadata,

  /// Final state: file is ready, waiting for Dart to acknowledge persistence.
  completedPendingAck,
  failed,
  cancelled,
  ;
}

class EnqueueDownloadRequest {
  final Track track;
  final String downloadDir;
  final String preferredQuality;

  const EnqueueDownloadRequest({
    required this.track,
    required this.downloadDir,
    required this.preferredQuality,
  });

  @override
  int get hashCode =>
      track.hashCode ^ downloadDir.hashCode ^ preferredQuality.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnqueueDownloadRequest &&
          runtimeType == other.runtimeType &&
          track == other.track &&
          downloadDir == other.downloadDir &&
          preferredQuality == other.preferredQuality;
}
