// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../plugin/models.dart';
import '../plugin/traits.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<BigInt> currentUnixEpochSecs() =>
    RustLib.instance.api.crateApiDownloaderUtilsCurrentUnixEpochSecs();

Future<BigInt> currentUnixEpochMillis() =>
    RustLib.instance.api.crateApiDownloaderUtilsCurrentUnixEpochMillis();

Future<String> generateTaskId() =>
    RustLib.instance.api.crateApiDownloaderUtilsGenerateTaskId();

/// Replace characters that are illegal on Windows/macOS/Linux file systems.
Future<String> sanitizeFileComponent(
        {required String value, required BigInt maxLen}) =>
    RustLib.instance.api.crateApiDownloaderUtilsSanitizeFileComponent(
        value: value, maxLen: maxLen);

/// Build a deterministic download file name from track metadata.
/// The 8-hex suffix is derived from the track ID so the same track always
/// produces the same file name suffix in the same process run (stored in
/// manifest at enqueue time, so stability across Rust versions is irrelevant).
Future<String> buildDownloadFileName(
        {required Track track, required String extension_}) =>
    RustLib.instance.api.crateApiDownloaderUtilsBuildDownloadFileName(
        track: track, extension_: extension_);

/// Infer an audio file extension from the optional format string or the URL path.
Future<String> guessExtensionFromUrl({Str? format, required String url}) =>
    RustLib.instance.api
        .crateApiDownloaderUtilsGuessExtensionFromUrl(format: format, url: url);

/// Split a media ID of the form `"pluginId::localId"` into its two parts.
/// Returns `None` if the separator is absent.
Future<(String, String)?> splitMediaId({required String mediaId}) =>
    RustLib.instance.api.crateApiDownloaderUtilsSplitMediaId(mediaId: mediaId);

/// Determine the total file size from response headers.
/// For a 206 response, the `Content-Range` header gives the full size.
/// For a 200 response, `Content-Length` gives the body size which we add
/// to `existing_size` (the bytes already downloaded before the request).
Future<BigInt?> extractTotalBytes(
        {required HeaderMap headers, required BigInt existingSize}) =>
    RustLib.instance.api.crateApiDownloaderUtilsExtractTotalBytes(
        headers: headers, existingSize: existingSize);

/// Remove a file if it exists; succeed silently if it does not.
Future<void> removeIfExists({required String path}) =>
    RustLib.instance.api.crateApiDownloaderUtilsRemoveIfExists(path: path);

/// Write `content` to `dest_path` atomically:
/// 1. Write to a `.tmp` sibling file.
/// 2. Rename the `.tmp` file over `dest_path`.
///
/// This ensures `dest_path` is never partially written on process crashes.
Future<void> atomicWrite(
        {required String destPath, required List<int> content}) =>
    RustLib.instance.api.crateApiDownloaderUtilsAtomicWrite(
        destPath: destPath, content: content);

/// Canonicalize an arbitrary quality string to "Low", "Medium", or "High".
Future<void> normalizeQuality({required String preference}) =>
    RustLib.instance.api
        .crateApiDownloaderUtilsNormalizeQuality(preference: preference);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HeaderMap>>
abstract class HeaderMap implements RustOpaqueInterface {}
