// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `deserialize_manifest_version`, `parse_plugin_version`, `validate`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `capabilities`, `check`, `created_at`, `from_file`, `has_capability`, `host_sites`, `icon`, `id`, `name`, `new`, `plugin_type`, `publisher`

/// Describes a required key/credential for a plugin.
///
/// JSON format:
/// ```json
/// {
///   "api_key": {
///     "description": "API key for authenticating",
///     "default": null,
///     "is_secret": true
///   }
/// }
/// ```
class KeyRequirement {
  /// Human-readable description of what this key is used for.
  final String description;

  /// Default value for this key. `None` means user must provide it.
  final String? defaultValue;

  /// Whether this key should be treated as a secret (masked in UI).
  final bool isSecret;

  const KeyRequirement({
    required this.description,
    this.defaultValue,
    required this.isSecret,
  });

  @override
  int get hashCode =>
      description.hashCode ^ defaultValue.hashCode ^ isSecret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyRequirement &&
          runtimeType == other.runtimeType &&
          description == other.description &&
          defaultValue == other.defaultValue &&
          isSecret == other.isSecret;
}

class Manifest {
  final int manifestVersion;
  final String id;
  final String name;
  final String version;
  final String type;
  final String description;
  final PluginPublisher publisher;
  final String license;
  final String homepage;
  final String? icon;
  final List<String> hostSite;
  final List<String> capabilities;
  final String? createdAt;

  /// Remote URL where this plugin was downloaded from.
  /// Used for impersonation detection - if two plugins have the same ID
  /// but different remote_url, it may indicate impersonation.
  final String? remoteUrl;

  /// Map of key name → requirement describing credentials the plugin needs.
  final Map<String, KeyRequirement> keysRequired;

  /// URL for the plugin's thumbnail/icon image.
  final String? thumbnailUrl;

  /// Whether this plugin acts as the primary content resolver (for search routing).
  final bool resolver;

  /// ISO 8601 timestamp of the last plugin update.
  final String? lastUpdated;

  const Manifest({
    required this.manifestVersion,
    required this.id,
    required this.name,
    required this.version,
    required this.type,
    required this.description,
    required this.publisher,
    required this.license,
    required this.homepage,
    this.icon,
    required this.hostSite,
    required this.capabilities,
    this.createdAt,
    this.remoteUrl,
    required this.keysRequired,
    this.thumbnailUrl,
    required this.resolver,
    this.lastUpdated,
  });

  @override
  int get hashCode =>
      manifestVersion.hashCode ^
      id.hashCode ^
      name.hashCode ^
      version.hashCode ^
      type.hashCode ^
      description.hashCode ^
      publisher.hashCode ^
      license.hashCode ^
      homepage.hashCode ^
      icon.hashCode ^
      hostSite.hashCode ^
      capabilities.hashCode ^
      createdAt.hashCode ^
      remoteUrl.hashCode ^
      keysRequired.hashCode ^
      thumbnailUrl.hashCode ^
      resolver.hashCode ^
      lastUpdated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Manifest &&
          runtimeType == other.runtimeType &&
          manifestVersion == other.manifestVersion &&
          id == other.id &&
          name == other.name &&
          version == other.version &&
          type == other.type &&
          description == other.description &&
          publisher == other.publisher &&
          license == other.license &&
          homepage == other.homepage &&
          icon == other.icon &&
          hostSite == other.hostSite &&
          capabilities == other.capabilities &&
          createdAt == other.createdAt &&
          remoteUrl == other.remoteUrl &&
          keysRequired == other.keysRequired &&
          thumbnailUrl == other.thumbnailUrl &&
          resolver == other.resolver &&
          lastUpdated == other.lastUpdated;
}

/// Plugin publisher information
class PluginPublisher {
  final String name;
  final String? url;
  final String? contact;
  final String? keyId;

  const PluginPublisher({
    required this.name,
    this.url,
    this.contact,
    this.keyId,
  });

  @override
  int get hashCode =>
      name.hashCode ^ url.hashCode ^ contact.hashCode ^ keyId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginPublisher &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          url == other.url &&
          contact == other.contact &&
          keyId == other.keyId;
}
