// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'models.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HttpMethod`, `MappingIds`, `SectionLink`, `Thumbnail`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class AlbumDetails {
  final AlbumSummary summary;
  final PagedTracks tracks;
  final String? description;

  const AlbumDetails({
    required this.summary,
    required this.tracks,
    this.description,
  });

  @override
  int get hashCode => summary.hashCode ^ tracks.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumDetails &&
          runtimeType == other.runtimeType &&
          summary == other.summary &&
          tracks == other.tracks &&
          description == other.description;
}

class AlbumSummary {
  final String id;
  final String title;
  final List<ArtistSummary> artists;
  final List<Artwork> thumbnails;
  final int? year;
  final String? url;

  const AlbumSummary({
    required this.id,
    required this.title,
    required this.artists,
    required this.thumbnails,
    this.year,
    this.url,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artists.hashCode ^
      thumbnails.hashCode ^
      year.hashCode ^
      url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artists == other.artists &&
          thumbnails == other.thumbnails &&
          year == other.year &&
          url == other.url;
}

class ArtistDetails {
  final ArtistSummary summary;
  final List<Track> topTracks;
  final PagedAlbums albums;
  final List<ArtistSummary> relatedArtists;
  final String? description;

  const ArtistDetails({
    required this.summary,
    required this.topTracks,
    required this.albums,
    required this.relatedArtists,
    this.description,
  });

  @override
  int get hashCode =>
      summary.hashCode ^
      topTracks.hashCode ^
      albums.hashCode ^
      relatedArtists.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtistDetails &&
          runtimeType == other.runtimeType &&
          summary == other.summary &&
          topTracks == other.topTracks &&
          albums == other.albums &&
          relatedArtists == other.relatedArtists &&
          description == other.description;
}

class ArtistSummary {
  final String id;
  final String name;
  final List<Artwork> thumbnails;
  final String? url;

  const ArtistSummary({
    required this.id,
    required this.name,
    required this.thumbnails,
    this.url,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ thumbnails.hashCode ^ url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtistSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          thumbnails == other.thumbnails &&
          url == other.url;
}

class Artwork {
  final String url;
  final String? urlLow;
  final String? urlHigh;
  final ImageLayout layout;

  const Artwork({
    required this.url,
    this.urlLow,
    this.urlHigh,
    required this.layout,
  });

  @override
  int get hashCode =>
      url.hashCode ^ urlLow.hashCode ^ urlHigh.hashCode ^ layout.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Artwork &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          urlLow == other.urlLow &&
          urlHigh == other.urlHigh &&
          layout == other.layout;
}

enum CardType {
  carousel,
  grid,
  vlist,
  news,
  ;
}

class ChartItem {
  final MediaItem item;
  final int rank;
  final Trend trend;
  final int? change;
  final int? previousRank;
  final int? peakRank;
  final int? weeksOnChart;

  const ChartItem({
    required this.item,
    required this.rank,
    required this.trend,
    this.change,
    this.previousRank,
    this.peakRank,
    this.weeksOnChart,
  });

  @override
  int get hashCode =>
      item.hashCode ^
      rank.hashCode ^
      trend.hashCode ^
      change.hashCode ^
      previousRank.hashCode ^
      peakRank.hashCode ^
      weeksOnChart.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChartItem &&
          runtimeType == other.runtimeType &&
          item == other.item &&
          rank == other.rank &&
          trend == other.trend &&
          change == other.change &&
          previousRank == other.previousRank &&
          peakRank == other.peakRank &&
          weeksOnChart == other.weeksOnChart;
}

class ChartSummary {
  final String id;
  final String title;
  final String? description;
  final List<Artwork> thumbnails;
  final String? updatedAt;
  final String? period;

  const ChartSummary({
    required this.id,
    required this.title,
    this.description,
    required this.thumbnails,
    this.updatedAt,
    this.period,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      description.hashCode ^
      thumbnails.hashCode ^
      updatedAt.hashCode ^
      period.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChartSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          description == other.description &&
          thumbnails == other.thumbnails &&
          updatedAt == other.updatedAt &&
          period == other.period;
}

enum ImageLayout {
  portrait,
  landscape,
  square,
  banner,
  circular,
  ;
}

class Lyrics {
  final String? plain;
  final String? synced;
  final String? copyright;

  const Lyrics({
    this.plain,
    this.synced,
    this.copyright,
  });

  @override
  int get hashCode => plain.hashCode ^ synced.hashCode ^ copyright.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Lyrics &&
          runtimeType == other.runtimeType &&
          plain == other.plain &&
          synced == other.synced &&
          copyright == other.copyright;
}

@freezed
sealed class MediaItem with _$MediaItem {
  const MediaItem._();

  const factory MediaItem.track(
    Track field0,
  ) = MediaItem_Track;
  const factory MediaItem.album(
    AlbumSummary field0,
  ) = MediaItem_Album;
  const factory MediaItem.artist(
    ArtistSummary field0,
  ) = MediaItem_Artist;
  const factory MediaItem.playlist(
    PlaylistSummary field0,
  ) = MediaItem_Playlist;
}

class PagedAlbums {
  final List<AlbumSummary> items;
  final String? nextPageToken;

  const PagedAlbums({
    required this.items,
    this.nextPageToken,
  });

  @override
  int get hashCode => items.hashCode ^ nextPageToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PagedAlbums &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextPageToken == other.nextPageToken;
}

class PagedMediaItems {
  final List<MediaItem> items;
  final String? nextPageToken;

  const PagedMediaItems({
    required this.items,
    this.nextPageToken,
  });

  @override
  int get hashCode => items.hashCode ^ nextPageToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PagedMediaItems &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextPageToken == other.nextPageToken;
}

class PagedTracks {
  final List<Track> items;
  final String? nextPageToken;

  const PagedTracks({
    required this.items,
    this.nextPageToken,
  });

  @override
  int get hashCode => items.hashCode ^ nextPageToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PagedTracks &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextPageToken == other.nextPageToken;
}

class PlaylistDetails {
  final PlaylistSummary summary;
  final PagedTracks tracks;
  final String? description;

  const PlaylistDetails({
    required this.summary,
    required this.tracks,
    this.description,
  });

  @override
  int get hashCode => summary.hashCode ^ tracks.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistDetails &&
          runtimeType == other.runtimeType &&
          summary == other.summary &&
          tracks == other.tracks &&
          description == other.description;
}

class PlaylistSummary {
  final String id;
  final String title;
  final String? owner;
  final List<Artwork> thumbnails;
  final int? trackCount;
  final String? url;

  const PlaylistSummary({
    required this.id,
    required this.title,
    this.owner,
    required this.thumbnails,
    this.trackCount,
    this.url,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      owner.hashCode ^
      thumbnails.hashCode ^
      trackCount.hashCode ^
      url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          owner == other.owner &&
          thumbnails == other.thumbnails &&
          trackCount == other.trackCount &&
          url == other.url;
}

class Section {
  final String id;
  final String title;
  final String? subtitle;
  final CardType cardType;
  final List<MediaItem> items;
  final String? moreLink;

  const Section({
    required this.id,
    required this.title,
    this.subtitle,
    required this.cardType,
    required this.items,
    this.moreLink,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      subtitle.hashCode ^
      cardType.hashCode ^
      items.hashCode ^
      moreLink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Section &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          subtitle == other.subtitle &&
          cardType == other.cardType &&
          items == other.items &&
          moreLink == other.moreLink;
}

class Track {
  final String id;
  final String title;
  final List<ArtistSummary> artists;
  final AlbumSummary? album;
  final BigInt? durationMs;
  final List<Artwork> thumbnails;
  final String? url;
  final bool isExplicit;
  final Lyrics? lyrics;

  const Track({
    required this.id,
    required this.title,
    required this.artists,
    this.album,
    this.durationMs,
    required this.thumbnails,
    this.url,
    required this.isExplicit,
    this.lyrics,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artists.hashCode ^
      album.hashCode ^
      durationMs.hashCode ^
      thumbnails.hashCode ^
      url.hashCode ^
      isExplicit.hashCode ^
      lyrics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Track &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artists == other.artists &&
          album == other.album &&
          durationMs == other.durationMs &&
          thumbnails == other.thumbnails &&
          url == other.url &&
          isExplicit == other.isExplicit &&
          lyrics == other.lyrics;
}

enum Trend {
  up,
  down,
  same,
  newEntry,
  unknown,
  ;
}
