// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'models.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HttpMethod`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class AlbumDetails {
  final AlbumSummary summary;
  final PagedTracks tracks;
  final String? description;

  const AlbumDetails({
    required this.summary,
    required this.tracks,
    this.description,
  });

  @override
  int get hashCode => summary.hashCode ^ tracks.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumDetails &&
          runtimeType == other.runtimeType &&
          summary == other.summary &&
          tracks == other.tracks &&
          description == other.description;
}

class AlbumSummary {
  final String id;
  final String title;
  final List<ArtistSummary> artists;
  final Artwork? thumbnail;
  final String? subtitle;
  final int? year;
  final String? url;

  const AlbumSummary({
    required this.id,
    required this.title,
    required this.artists,
    this.thumbnail,
    this.subtitle,
    this.year,
    this.url,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artists.hashCode ^
      thumbnail.hashCode ^
      subtitle.hashCode ^
      year.hashCode ^
      url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artists == other.artists &&
          thumbnail == other.thumbnail &&
          subtitle == other.subtitle &&
          year == other.year &&
          url == other.url;
}

class ArtistDetails {
  final ArtistSummary summary;
  final List<Track> topTracks;
  final PagedAlbums albums;
  final List<ArtistSummary> relatedArtists;
  final String? description;

  const ArtistDetails({
    required this.summary,
    required this.topTracks,
    required this.albums,
    required this.relatedArtists,
    this.description,
  });

  @override
  int get hashCode =>
      summary.hashCode ^
      topTracks.hashCode ^
      albums.hashCode ^
      relatedArtists.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtistDetails &&
          runtimeType == other.runtimeType &&
          summary == other.summary &&
          topTracks == other.topTracks &&
          albums == other.albums &&
          relatedArtists == other.relatedArtists &&
          description == other.description;
}

class ArtistSummary {
  final String id;
  final String name;
  final Artwork? thumbnail;
  final String? subtitle;
  final String? url;

  const ArtistSummary({
    required this.id,
    required this.name,
    this.thumbnail,
    this.subtitle,
    this.url,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      thumbnail.hashCode ^
      subtitle.hashCode ^
      url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtistSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          thumbnail == other.thumbnail &&
          subtitle == other.subtitle &&
          url == other.url;
}

class Artwork {
  final String url;
  final String? urlLow;
  final String? urlHigh;
  final ImageLayout layout;

  const Artwork({
    required this.url,
    this.urlLow,
    this.urlHigh,
    required this.layout,
  });

  @override
  int get hashCode =>
      url.hashCode ^ urlLow.hashCode ^ urlHigh.hashCode ^ layout.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Artwork &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          urlLow == other.urlLow &&
          urlHigh == other.urlHigh &&
          layout == other.layout;
}

enum CardType {
  carousel,
  grid,
  vlist,
  news,
  ;
}

class ChartItem {
  final MediaItem item;
  final int rank;
  final Trend trend;
  final int? change;
  final int? peakRank;
  final int? weeksOnChart;

  const ChartItem({
    required this.item,
    required this.rank,
    required this.trend,
    this.change,
    this.peakRank,
    this.weeksOnChart,
  });

  @override
  int get hashCode =>
      item.hashCode ^
      rank.hashCode ^
      trend.hashCode ^
      change.hashCode ^
      peakRank.hashCode ^
      weeksOnChart.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChartItem &&
          runtimeType == other.runtimeType &&
          item == other.item &&
          rank == other.rank &&
          trend == other.trend &&
          change == other.change &&
          peakRank == other.peakRank &&
          weeksOnChart == other.weeksOnChart;
}

class ChartSummary {
  final String id;
  final String title;
  final String? description;
  final Artwork? thumbnail;

  const ChartSummary({
    required this.id,
    required this.title,
    this.description,
    this.thumbnail,
  });

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ description.hashCode ^ thumbnail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChartSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          description == other.description &&
          thumbnail == other.thumbnail;
}

class EntitySuggestion {
  final String id;
  final String title;
  final String? subtitle;
  final EntityType kind;
  final SuggestionArtwork? thumbnail;

  const EntitySuggestion({
    required this.id,
    required this.title,
    this.subtitle,
    required this.kind,
    this.thumbnail,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      subtitle.hashCode ^
      kind.hashCode ^
      thumbnail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntitySuggestion &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          subtitle == other.subtitle &&
          kind == other.kind &&
          thumbnail == other.thumbnail;
}

enum EntityType {
  track,
  album,
  artist,
  playlist,
  genre,
  unknown,
  ;
}

enum ImageLayout {
  portrait,
  landscape,
  square,
  banner,
  circular,
  ;
}

class Lyrics {
  final String? plain;
  final String? synced;
  final String? copyright;

  const Lyrics({
    this.plain,
    this.synced,
    this.copyright,
  });

  @override
  int get hashCode => plain.hashCode ^ synced.hashCode ^ copyright.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Lyrics &&
          runtimeType == other.runtimeType &&
          plain == other.plain &&
          synced == other.synced &&
          copyright == other.copyright;
}

class LyricsLine {
  final int startMs;
  final int? durationMs;
  final String content;
  final List<LyricsToken>? tokens;

  const LyricsLine({
    required this.startMs,
    this.durationMs,
    required this.content,
    this.tokens,
  });

  @override
  int get hashCode =>
      startMs.hashCode ^
      durationMs.hashCode ^
      content.hashCode ^
      tokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricsLine &&
          runtimeType == other.runtimeType &&
          startMs == other.startMs &&
          durationMs == other.durationMs &&
          content == other.content &&
          tokens == other.tokens;
}

class LyricsMatch {
  final String id;
  final String title;
  final String artist;
  final String? album;
  final BigInt? durationMs;
  final LyricsSyncType syncType;

  const LyricsMatch({
    required this.id,
    required this.title,
    required this.artist,
    this.album,
    this.durationMs,
    required this.syncType,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationMs.hashCode ^
      syncType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricsMatch &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationMs == other.durationMs &&
          syncType == other.syncType;
}

class LyricsMetadata {
  final String? source;
  final String? author;
  final String? language;
  final String? copyright;
  final bool isVerified;

  const LyricsMetadata({
    this.source,
    this.author,
    this.language,
    this.copyright,
    required this.isVerified,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      author.hashCode ^
      language.hashCode ^
      copyright.hashCode ^
      isVerified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricsMetadata &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          author == other.author &&
          language == other.language &&
          copyright == other.copyright &&
          isVerified == other.isVerified;
}

enum LyricsSyncType {
  none,
  line,
  syllable,
  ;
}

class LyricsToken {
  final int offsetMs;
  final String text;

  const LyricsToken({
    required this.offsetMs,
    required this.text,
  });

  @override
  int get hashCode => offsetMs.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricsToken &&
          runtimeType == other.runtimeType &&
          offsetMs == other.offsetMs &&
          text == other.text;
}

@freezed
sealed class MediaItem with _$MediaItem {
  const MediaItem._();

  const factory MediaItem.track(
    Track field0,
  ) = MediaItem_Track;
  const factory MediaItem.album(
    AlbumSummary field0,
  ) = MediaItem_Album;
  const factory MediaItem.artist(
    ArtistSummary field0,
  ) = MediaItem_Artist;
  const factory MediaItem.playlist(
    PlaylistSummary field0,
  ) = MediaItem_Playlist;
}

class PagedAlbums {
  final List<AlbumSummary> items;
  final String? nextPageToken;

  const PagedAlbums({
    required this.items,
    this.nextPageToken,
  });

  @override
  int get hashCode => items.hashCode ^ nextPageToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PagedAlbums &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextPageToken == other.nextPageToken;
}

class PagedMediaItems {
  final List<MediaItem> items;
  final String? nextPageToken;

  const PagedMediaItems({
    required this.items,
    this.nextPageToken,
  });

  @override
  int get hashCode => items.hashCode ^ nextPageToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PagedMediaItems &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextPageToken == other.nextPageToken;
}

class PagedTracks {
  final List<Track> items;
  final String? nextPageToken;

  const PagedTracks({
    required this.items,
    this.nextPageToken,
  });

  @override
  int get hashCode => items.hashCode ^ nextPageToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PagedTracks &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          nextPageToken == other.nextPageToken;
}

class PlaylistDetails {
  final PlaylistSummary summary;
  final PagedTracks tracks;
  final String? description;

  const PlaylistDetails({
    required this.summary,
    required this.tracks,
    this.description,
  });

  @override
  int get hashCode => summary.hashCode ^ tracks.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistDetails &&
          runtimeType == other.runtimeType &&
          summary == other.summary &&
          tracks == other.tracks &&
          description == other.description;
}

class PlaylistSummary {
  final String id;
  final String title;
  final String? owner;
  final Artwork thumbnail;
  final String? url;

  const PlaylistSummary({
    required this.id,
    required this.title,
    this.owner,
    required this.thumbnail,
    this.url,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      owner.hashCode ^
      thumbnail.hashCode ^
      url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          owner == other.owner &&
          thumbnail == other.thumbnail &&
          url == other.url;
}

class PluginLyrics {
  final String? plain;
  final String? lrc;
  final List<LyricsLine>? lines;
  final bool isInstrumental;
  final LyricsSyncType syncType;

  const PluginLyrics({
    this.plain,
    this.lrc,
    this.lines,
    required this.isInstrumental,
    required this.syncType,
  });

  @override
  int get hashCode =>
      plain.hashCode ^
      lrc.hashCode ^
      lines.hashCode ^
      isInstrumental.hashCode ^
      syncType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginLyrics &&
          runtimeType == other.runtimeType &&
          plain == other.plain &&
          lrc == other.lrc &&
          lines == other.lines &&
          isInstrumental == other.isInstrumental &&
          syncType == other.syncType;
}

enum Quality {
  low,
  medium,
  high,
  lossless,
  ;
}

class Section {
  final String id;
  final String title;
  final String? subtitle;
  final CardType cardType;
  final List<MediaItem> items;
  final String? moreLink;

  const Section({
    required this.id,
    required this.title,
    this.subtitle,
    required this.cardType,
    required this.items,
    this.moreLink,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      subtitle.hashCode ^
      cardType.hashCode ^
      items.hashCode ^
      moreLink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Section &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          subtitle == other.subtitle &&
          cardType == other.cardType &&
          items == other.items &&
          moreLink == other.moreLink;
}

enum SegmentType {
  intro,
  outro,
  sponsor,
  selfPromo,
  interaction,
  musicOfftopic,
  chapter,
  filler,
  unknown,
  ;
}

class StreamSource {
  final String url;
  final Quality quality;
  final String format;
  final List<(String, String)>? headers;
  final BigInt? expiresAt;

  const StreamSource({
    required this.url,
    required this.quality,
    required this.format,
    this.headers,
    this.expiresAt,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      quality.hashCode ^
      format.hashCode ^
      headers.hashCode ^
      expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreamSource &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          quality == other.quality &&
          format == other.format &&
          headers == other.headers &&
          expiresAt == other.expiresAt;
}

@freezed
sealed class Suggestion with _$Suggestion {
  const Suggestion._();

  const factory Suggestion.query(
    String field0,
  ) = Suggestion_Query;
  const factory Suggestion.entity(
    EntitySuggestion field0,
  ) = Suggestion_Entity;
}

class SuggestionArtwork {
  final String url;
  final String? urlLow;

  const SuggestionArtwork({
    required this.url,
    this.urlLow,
  });

  @override
  int get hashCode => url.hashCode ^ urlLow.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SuggestionArtwork &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          urlLow == other.urlLow;
}

class Track {
  final String id;
  final String title;
  final List<ArtistSummary> artists;
  final AlbumSummary? album;
  final BigInt? durationMs;
  final Artwork thumbnail;
  final String? url;
  final bool isExplicit;
  final Lyrics? lyrics;

  const Track({
    required this.id,
    required this.title,
    required this.artists,
    this.album,
    this.durationMs,
    required this.thumbnail,
    this.url,
    required this.isExplicit,
    this.lyrics,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artists.hashCode ^
      album.hashCode ^
      durationMs.hashCode ^
      thumbnail.hashCode ^
      url.hashCode ^
      isExplicit.hashCode ^
      lyrics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Track &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artists == other.artists &&
          album == other.album &&
          durationMs == other.durationMs &&
          thumbnail == other.thumbnail &&
          url == other.url &&
          isExplicit == other.isExplicit &&
          lyrics == other.lyrics;
}

class TrackMetadata {
  final String title;
  final String artist;
  final String? album;
  final BigInt? durationMs;

  const TrackMetadata({
    required this.title,
    required this.artist,
    this.album,
    this.durationMs,
  });

  @override
  int get hashCode =>
      title.hashCode ^ artist.hashCode ^ album.hashCode ^ durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackMetadata &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationMs == other.durationMs;
}

class TrackSegment {
  final SegmentType segmentType;
  final BigInt startMs;
  final BigInt endMs;
  final String? title;
  final bool isSkippable;

  const TrackSegment({
    required this.segmentType,
    required this.startMs,
    required this.endMs,
    this.title,
    required this.isSkippable,
  });

  @override
  int get hashCode =>
      segmentType.hashCode ^
      startMs.hashCode ^
      endMs.hashCode ^
      title.hashCode ^
      isSkippable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackSegment &&
          runtimeType == other.runtimeType &&
          segmentType == other.segmentType &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          title == other.title &&
          isSkippable == other.isSkippable;
}

enum Trend {
  up,
  down,
  same,
  newEntry,
  reEntry,
  unknown,
  ;
}
