// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'downloader/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'plugin/models.dart';
import 'plugin/plugin.dart';

// These functions are ignored because they are not marked as `pub`: `emit`, `fail_task`, `get_task`, `handle_progress_update`, `persist_manifest`, `remove_task`, `run_task`, `set_task_state`, `snapshot_for`, `spawn_worker`, `update_retrying`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `drop`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DownloadManager>>
abstract class DownloadManager implements RustOpaqueInterface {
  /// Called by Dart after successfully persisting a completed download to its
  /// database. Removes the task from the manager.
  Future<bool> acknowledgePersisted({required String taskId});

  /// Request cancellation of a task.
  /// `delete_partial`: if `true`, remove the .part file too.
  Future<bool> cancelTask(
      {required String taskId, required bool deletePartial});

  /// Enqueue a new download. Returns the task ID.
  Future<String> enqueue({required EnqueueDownloadRequest request});

  /// Snapshot all current tasks.
  Future<List<DownloadTaskSnapshot>> getSnapshots();

  /// Attach the FRB event sink. Call this once from Dart after creating the
  /// manager. Any events buffered before this call are drained immediately.
  Stream<DownloadManagerEvent> initEventStream();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DownloadManager> newInstance(
          {required PluginManager pluginManager,
          required String stateDir,
          required String tempDir,
          required int maxConcurrentTasks}) =>
      RustLib.instance.api.crateApiDownloaderDownloadManagerNew(
          pluginManager: pluginManager,
          stateDir: stateDir,
          tempDir: tempDir,
          maxConcurrentTasks: maxConcurrentTasks);

  /// Signal a running download to pause. Returns `false` if the task does not exist.
  Future<bool> pauseTask({required String taskId});

  /// Restore tasks persisted from a previous run.
  /// Emits `RecoverySummary` after reconciling state.
  Future<List<DownloadTaskSnapshot>> restoreTasks();

  /// Queue a paused/failed task for another download attempt.
  Future<bool> resumeTask({required String taskId});
}
