// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_cover_art`, `is_audio_file`, `walk_directory`

Future<LocalTrackMeta> readAudioMetadata(
        {required String filePath, required String coverCacheDir}) =>
    RustLib.instance.api.crateApiLocalMusicReadAudioMetadata(
        filePath: filePath, coverCacheDir: coverCacheDir);

Future<List<LocalTrackMeta>> scanAudioFiles(
        {required List<String> directories, required String coverCacheDir}) =>
    RustLib.instance.api.crateApiLocalMusicScanAudioFiles(
        directories: directories, coverCacheDir: coverCacheDir);

class LocalTrackMeta {
  final String filePath;
  final String? title;
  final List<String> artists;
  final String? album;
  final String? albumArtist;
  final int? year;
  final String? genre;
  final BigInt? durationMs;
  final String? coverArtPath;
  final BigInt fileSize;

  const LocalTrackMeta({
    required this.filePath,
    this.title,
    required this.artists,
    this.album,
    this.albumArtist,
    this.year,
    this.genre,
    this.durationMs,
    this.coverArtPath,
    required this.fileSize,
  });

  @override
  int get hashCode =>
      filePath.hashCode ^
      title.hashCode ^
      artists.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      year.hashCode ^
      genre.hashCode ^
      durationMs.hashCode ^
      coverArtPath.hashCode ^
      fileSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalTrackMeta &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath &&
          title == other.title &&
          artists == other.artists &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          year == other.year &&
          genre == other.genre &&
          durationMs == other.durationMs &&
          coverArtPath == other.coverArtPath &&
          fileSize == other.fileSize;
}
